name: Kenna-Dependabot-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name:  Run Toolkit    
      uses: addnab/docker-run-action@v3
      with:
        image: kennasecurity/toolkit:latest
        run:  bundle exec ruby toolkit.rb task=github_dependabot github_token=${{secrets.GH_TOKEN}} github_organization_name=${{secrets.GH_ORG_NAME}} kenna_connector_id=158100 kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=$${{secrets.KENNA_API_KEY}}
