name: Kenna-CodeScanning-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name:  Run Toolkit    
      uses: addnab/docker-run-action@v3
      with:
        image: kennasecurity/toolkit:latest
        run:  echo ${{secrets.GH_TOKEN}};bundle exec ruby toolkit.rb task=github_code_scanning github_token=${{secrets.GH_TOKEN}} kenna_connector_id=158099 github_username=${{secrets.GH_USERNAME}} kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=${{secrets.KENNA_API_KEY}} github_repositories=${{secrets.GH_REPOS}}
