name: Kenna-Dependabot-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaSecurity/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install --without development test
    - name:  Run Toolkit
      run : bundle exec ruby toolkit.rb task=github_dependabot github_token=$GITHUB_TOKEN github_organization_name=$GITHUB_ORGANIZATION_NAME kenna_connector_id=$KENNA_CONNECTOR_ID kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=$KENNA_API_KEY
      env:
        GITHUB_TOKEN=: "${{secrets.GH_TOKEN}}"
        GITHUB_ORGANIZATION_NAME=: "${{secrets.GH_ORG_NAME}}"
        KENNA_API_KEY=: "${{secrets.KENNA_API_KEY}}"
        KENNA_CONNECTOR_ID=: "${{secrets.KENNA_DEP_CONNECTOR_ID}}"
