name: Kenna-CodeScanning-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaSecurity/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Install dependencies
      run: bundle install --without development test
    - name:  Run Toolkit
      run : bundle exec ruby toolkit.rb task=github_code_scanning github_token=$GITHUB_TOKEN kenna_connector_id=158099 github_username=$GITHUB_USERNAME kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=$KENNA_API_KEY github_repositories=$GITHUB_REPOSITORIES
      env:
        GITHUB_TOKEN=: "${{secrets.GH_TOKEN}}"
        GITHUB_USERNAME=: "${{secrets.GH_USERNAME}}"
        GITHUB_REPOSITORIES=: "${{secrets.GH_REPOS}}"
        KENNA_API_KEY=: "${{secrets.KENNA_API_KEY}}"
