name: Kenna-Dependabot-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: abirismyname/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install --without development test
    - name:  Run Toolkit
      run : exec bundle exec ruby toolkit.rb task=github_dependabot github_token=${GH_TOKEN} github_organization_name=${GH_ORG_NAME} kenna_connector_id=158100 kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=${KENNA_API_KEY}
      env:
        GH_TOKEN: "${{secrets.GH_TOKEN}}"
        GH_ORG_NAME: "${{secrets.GH_ORG_NAME}}"
        KENNA_API_KEY: "${{secrets.KENNA_API_KEY}}"
